(part "nRF52833-QDAA-R"
    (packageRef "QFN40P500X500X90-41N")
    (interface
        (port "1" (symbPinId 1) (portName "DEC1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "P0.00/XL1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "P0.01/XL2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "P0.04/AIN2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "P0.05/AIN3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "P1.09") (portType INOUT))
        (port "7" (symbPinId 7) (portName "P0.11") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VDDH") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VBUS") (portType INOUT))
        (port "11" (symbPinId 11) (portName "DECUSB") (portType INOUT))
        (port "12" (symbPinId 12) (portName "D-") (portType INOUT))
        (port "13" (symbPinId 13) (portName "D+") (portType INOUT))
        (port "14" (symbPinId 14) (portName "P0.15") (portType INOUT))
        (port "15" (symbPinId 15) (portName "P0.17") (portType INOUT))
        (port "16" (symbPinId 16) (portName "P0.18/NRESET") (portType INOUT))
        (port "17" (symbPinId 17) (portName "P0.20") (portType INOUT))
        (port "18" (symbPinId 18) (portName "VDD_2") (portType INOUT))
        (port "19" (symbPinId 19) (portName "SWDIO") (portType INOUT))
        (port "20" (symbPinId 20) (portName "SWDCLK") (portType INOUT))
        (port "21" (symbPinId 21) (portName "DEC5") (portType INOUT))
        (port "22" (symbPinId 22) (portName "P0.09/NFC1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "P0.10/NFC2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "ANT") (portType INOUT))
        (port "25" (symbPinId 25) (portName "VSS_PA") (portType INOUT))
        (port "26" (symbPinId 26) (portName "DEC6") (portType INOUT))
        (port "27" (symbPinId 27) (portName "DEC3") (portType INOUT))
        (port "28" (symbPinId 28) (portName "XC1") (portType INOUT))
        (port "29" (symbPinId 29) (portName "XC2") (portType INOUT))
        (port "30" (symbPinId 30) (portName "VDD_3") (portType INOUT))
        (port "31" (symbPinId 31) (portName "P0.03/AIN1") (portType INOUT))
        (port "32" (symbPinId 32) (portName "P0.02/AIN0") (portType INOUT))
        (port "33" (symbPinId 33) (portName "P0.28/AIN4") (portType INOUT))
        (port "34" (symbPinId 34) (portName "P0.29/AIN5") (portType INOUT))
        (port "35" (symbPinId 35) (portName "P0.30/AIN6") (portType INOUT))
        (port "36" (symbPinId 36) (portName "P0.31/AIN7") (portType INOUT))
        (port "37" (symbPinId 37) (portName "VSS_1") (portType INOUT))
        (port "38" (symbPinId 38) (portName "DEC4") (portType INOUT))
        (port "39" (symbPinId 39) (portName "DCC") (portType INOUT))
        (port "40" (symbPinId 40) (portName "VDD_4") (portType INOUT))
        (port "41" (symbPinId 41) (portName "VSS_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "949-NRF52833-QDAA-R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nordic-Semiconductor/nRF52833-QDAA-R?qs=xZ%2FP%252Ba9zWqYrk%252Bfy26NOZQ%3D%3D")
    (property "Manufacturer_Name" "Nordic Semiconductor")
    (property "Manufacturer_Part_Number" "nRF52833-QDAA-R")
    (property "Description" "RF System on a Chip - SoC nRF52833-QDAA QFN 40L 5x5")
    (property "Datasheet_Link" "https://infocenter.nordicsemi.com/pdf/nRF52833_PS_v1.3.pdf")
    (property "symbolName1" "nRF52833-QDAA-R")
)
